service: serverless-lambda-python

#useDotenv: true

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-north-1

plugins:
  - serverless-python-requirements  # we use node to install the dependency called serverless-python...
  - serverless-dotenv-plugin # rrquested in order to use env variables

package: 
  individually: true  # include only specified files in the lambda package

functions:
  StartStop:
    name: Bolt-PO-StartStopEC2
    handler: bolt_startstop.handler
    environment:
      AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    module: start_stop_ec2
    description: Bolt-PO lambda function to start or stop the associated EC2 machines
    timeout: 120 # in seconds, max allowed time to run
    memorySize: 128 # in mb
    package: 
      patterns:  # include or exclude files in the lambda package
        - "!node_modules/**"  # exclude the node modules
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
  CleanUp:
    name: Bolt-PO-CleanUp
    handler: bolt_clean.handler
    module: cleanup_s3
    description: Bolt-PO lambda function to clean up input files
    timeout: 10 # in seconds, max allowed time to run
    memorySize: 128 # in mb
    package: 
      patterns:  # include or exclude files in the lambda package
        - "!node_modules/**"  # exclude the node modules
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
  CheckHealth:
    name: Bolt-PO-CheckHealth
    handler: bolt_check.handler
    module: check_health
    description: Bolt-PO lambda function to check EC2-API containers health
    timeout: 5
    memorySize: 128
    package: 
      patterns:  # include or exclude files in the lambda package
        - "!node_modules/**"  # exclude the node modules
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
  ConvertSuppDict:
    name: Bolt-PO-Convert-SuppDict
    handler: bolt_suppdict.handler
    module: convert_suppdict
    description: Bolt-PO lambda function to convert suppliers dictionary
    timeout: 10 # in seconds, max allowed time to run
    memorySize: 128 # in mb
    package: 
      patterns:  # include or exclude files in the lambda package
        - "!node_modules/**"  # exclude the node modules
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
