service: serverless-lambda-python

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-north-1

plugins:
  - serverless-python-requirements  # we use node to install the dependency called serverless-python...

package: 
  individually: true  # include only specified files in the lambda package

functions:
  theLambda:
    name: test-lambda
    handler: lambda.handler
    description: simple test-lambda to showcase the gh action
    timeout: 5 # in seconds, max allowed time to run
    memorySize: 128 # in mb
    package: 
      patterns:  # include or exclude files in the lambda package
        - "!node_modules/**"  # exclude the node modules
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
  anotherLambda:
    name: hello-lambda
    handler: bolt_check.handler
    description: another lambda to showcase the deployment of two functions
    timeout: 5
    memorySize: 128
    package: 
      patterns:  # include or exclude files in the lambda package
        - "!node_modules/**"  # exclude the node modules
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"